using System;
using System.Collections.Generic;

namespace Unisol.Web.Entities.Database.UnisolModels
{
    public partial class HrpPayrollJournal
    {
        public int Id { get; set; }
        public string EmpNo { get; set; }
        public string Speriod { get; set; }
        public DateTime? RDate { get; set; }
        public decimal? EmploymentExpenses { get; set; }
        public decimal? CautionMoney { get; set; }
        public decimal? PrepaidFeesStudents { get; set; }
        public decimal? ProvisionForAuditFees { get; set; }
        public decimal? CdfConstituencyDevelopmentFund { get; set; }
        public decimal? LongTermLiabilities { get; set; }
        public decimal? AcademicFieldTrips { get; set; }
        public decimal? LibraryExpenses { get; set; }
        public decimal? PrintingPublications { get; set; }
        public decimal? InternetServices { get; set; }
        public decimal? TelephoneExpenses { get; set; }
        public decimal? TradeAndOtherPayables { get; set; }
        public decimal? TeachingMaterialExpenses { get; set; }
        public decimal? BankChargesCommissions { get; set; }
        public decimal? TradeCreditors { get; set; }
        public decimal? ProjectsRetentionMoney { get; set; }
        public decimal? PartTimeLecturers { get; set; }
        public decimal? StaffMedicalClaims { get; set; }
        public decimal? AccruedStatutoryOtherDeductions { get; set; }
        public decimal? OtherLiabilitiesProvisions { get; set; }
        public decimal? GraduationExpenses { get; set; }
        public decimal? SupportServices { get; set; }
        public decimal? MaintenanceOfPlaygroundsParks { get; set; }
        public decimal? MedicalExpenses { get; set; }
        public decimal? StaffAndStudentsWelfare { get; set; }
        public decimal? PurchaseOfUniformsClothing { get; set; }
        public decimal? PublicCelebrationsStaffWelfare { get; set; }
        public decimal? AdministrationCosts { get; set; }
        public decimal? ExternalExaminers { get; set; }
        public decimal? OpenCulturalDayExpenses { get; set; }
        public decimal? PersonalEmoluments { get; set; }
        public decimal? GratuityPensionContributions { get; set; }
        public decimal? HouseAllowances { get; set; }
        public decimal? PassageLeaveAllowance { get; set; }
        public decimal? OtherPersonalAllowances { get; set; }
        public decimal? AdministrationAcademicAndCentralServicesExpenses { get; set; }
        public decimal? TravellingAccomodation { get; set; }
        public decimal? PostalTelegrams { get; set; }
        public decimal? PurchaseOfStationary { get; set; }
        public decimal? AuditFeesExpenses { get; set; }
        public decimal? InsuranceExpenses { get; set; }
        public decimal? LegalExpenses { get; set; }
        public decimal? StrategicPlanMasterPlanDesign { get; set; }
        public decimal? SecurityServices { get; set; }
        public decimal? TeachingPracticeFieldAttachment { get; set; }
        public decimal? AcademicTeachingResearchConsultancyExtension { get; set; }
        public decimal? UniversityOutreachProgrammeExhibition { get; set; }
        public decimal? DeansSenateComitteesConfrenceExpenses { get; set; }
        public decimal? UtilitiesElectricityWaterConservancy { get; set; }
        public decimal? PaymentOfRentRates { get; set; }
        public decimal? MaintenanceOfCateringHostelFacilities { get; set; }
        public decimal? CleaningMaterialsDetergents { get; set; }
        public decimal? MaintainaceOfPlantFurnitureEquipment { get; set; }
        public decimal? MaintenanceOfBuildingsStations { get; set; }
        public decimal? ContractServicesSubscriptions { get; set; }
        public decimal? MaintenanceOfWaterSuppliersSewerage { get; set; }
        public decimal? CouncilCouncilCommitteesExpenses { get; set; }
        public decimal? AdvertisingPublicity { get; set; }
        public decimal? RecruitmentTrainingExpenses { get; set; }
        public decimal? CommercialEnterprisesIguWorkingCapital { get; set; }
        public decimal? BankLoans { get; set; }
        public decimal? StaffInsurance { get; set; }
        public decimal? ExaminationExpenses { get; set; }
        public decimal? Newspapers { get; set; }
        public decimal? BankTransfers { get; set; }
        public decimal? MaintenanceOfMotorVehicles { get; set; }
        public decimal? ExternalTravellingAccomodation { get; set; }
        public decimal? PayrollRecoveries { get; set; }
        public decimal? Sponsorships { get; set; }
        public decimal? PostgraduateSupervision { get; set; }
        public decimal? Crops { get; set; }
        public decimal? MaizeExpenses { get; set; }
        public decimal? WheatExpenses { get; set; }
        public decimal? BarleyExpenses { get; set; }
        public decimal? MilletExpenses { get; set; }
        public decimal? Livestock { get; set; }
        public decimal? DairyExpenses { get; set; }
        public decimal? PiggeryExpenses { get; set; }
        public decimal? AppiaryExpenses { get; set; }
        public decimal? PoultryExpenses { get; set; }
        public decimal? RabbitsExpenses { get; set; }
        public decimal? HelbLoanStudents { get; set; }
        public decimal? HelbBursariesStudents { get; set; }
        public decimal? NetPay { get; set; }
        public decimal? Paye { get; set; }
        public decimal? Nssf { get; set; }
        public decimal? Nhif { get; set; }
        public decimal? HelbLoanRepaymentStaff { get; set; }
        public decimal? Welfares { get; set; }
        public decimal? Pension { get; set; }
        public decimal? UnionDues { get; set; }
        public decimal? CommuterAllowances { get; set; }
        public decimal? SalaryRecovery { get; set; }
        public decimal? CapitalCreditors { get; set; }
        public decimal? ContigentExpenses { get; set; }
        public decimal? CommissionerOfDomesticTaxesWithholdingTax { get; set; }
        public decimal? VatTaxes { get; set; }
        public decimal? RetentionContractor { get; set; }
        public decimal? UnallocatedFee { get; set; }
        public decimal? DepreciationPlantAndEquipment { get; set; }
        public decimal? DepreciationComputersAndAssesories { get; set; }
        public decimal? DepreciationFurnitureAndFittings { get; set; }
        public decimal? DepreciationMotorVehicles { get; set; }
        public decimal? AccumulatedDepreciationBuilding { get; set; }
        public decimal? AccumulatedDepreciationMotorVehicles { get; set; }
        public decimal? AccumulatedDepreciationFurnitureAndFittings { get; set; }
        public decimal? AccumulatedDepreciationPlantAndEquipment { get; set; }
        public decimal? OtherGainsLoss { get; set; }
        public decimal? GainLossOnBiologicalAssets { get; set; }
        public decimal? GainLossOnDisposalOfAssets { get; set; }
        public decimal? IncreaseDecreaseInProvisionForBadDebts { get; set; }
        public decimal? GainLossOnForeignExchangeTransactions { get; set; }
        public decimal? ProvisionForBadDebts { get; set; }
        public decimal? OfficialEntertainment { get; set; }
        public decimal? ContractedEmployees { get; set; }
        public decimal? PartTimeClaims { get; set; }
        public decimal? PsspServiceProvidersDisbursements { get; set; }
        public decimal? LegalAttachments { get; set; }
        public decimal? ChancellorsExpenses { get; set; }
        public decimal? PurchaseOfGowns { get; set; }
        public decimal? FinanceCharges { get; set; }
        public decimal? InterestCharges { get; set; }
        public decimal? AccumulatedDepreciationComputersAndAccessories { get; set; }
        public decimal? ResearchFundAccounts { get; set; }
        public decimal? ShowAndAgribusinessExpenses { get; set; }
        public decimal? ErpSytemMentainance { get; set; }
        public decimal? OfficeRunningExpenses { get; set; }
        public decimal? IgaExpenses { get; set; }
        public decimal? CateringExpenses { get; set; }
        public decimal? CollaboratingExpense { get; set; }
        public decimal? HireOfMotorVehiclesExpense { get; set; }
        public decimal? GuestHouseExpense { get; set; }
        public decimal? BookShopExpenses { get; set; }
        public decimal? FisheriesExpense { get; set; }
        public decimal? ConferenceWorkshopsExpenses { get; set; }
        public decimal? UoesoRentExpenses { get; set; }
        public decimal? IncomeTaxPartTimeClaims { get; set; }
        public decimal? WithHoldingVatTaxWhvat { get; set; }
        public decimal? EiaExpenses { get; set; }
        public decimal? InterUniversityGamesSports { get; set; }
        public decimal? TransportFuelExpenses { get; set; }
        public decimal? UniversityFundedResearchExpenses { get; set; }
        public decimal? StudentsWelfareOtherActivities { get; set; }
        public decimal? AccumulatedDepreciationLibraryBooks { get; set; }
        public decimal? DepreciationLibraryBooks { get; set; }
        public decimal? LibraryPeriodicalsJournals { get; set; }
        public decimal? RentPayable { get; set; }
        public decimal? DonorFundedResearchReceipts { get; set; }
        public decimal? CouncilSittingAllowance { get; set; }
        public decimal? CouncilTravellingAndAccomodation { get; set; }
        public decimal? CouncilMealsRefreshments { get; set; }
        public decimal? CouncilOtherExpenses { get; set; }
        public decimal? DepreciationBuildings { get; set; }
        public decimal? FarmExpensesOld { get; set; }
        public decimal? FarmExpenses { get; set; }
        public decimal? ForestryAndWoodScienceExpenses { get; set; }
        public decimal? MaintenanceOfComputersPrintersCopiers { get; set; }
        public decimal? DonorFundedResearchDisbursements { get; set; }
        public decimal? AccruedExpenses { get; set; }
        public decimal? AccumulatedArmotizationOfLand { get; set; }
        public decimal? AccummulatedArmotizationDepreciation { get; set; }
        public decimal? ArmotizationDepreciationExpenses { get; set; }
        public decimal? UesoExpenses { get; set; }
        public decimal? UoEsoFunds { get; set; }
        public decimal? Saccos { get; set; }
        public decimal? UoEsoExpenses { get; set; }
        public decimal? OtherIgaExpenses { get; set; }
        public decimal? CustomerPrepayments { get; set; }
        public decimal? ArmotizationOfLand { get; set; }
        public decimal? UoEsoFundsReceipts { get; set; }
        public decimal? LandTrasferExpenses { get; set; }
        public decimal? PerformanceContracting { get; set; }
        public decimal? IsoQualityAssuranceExpenses { get; set; }
        public decimal? AccreditationAdmissionRegistrationExpenses { get; set; }
        public decimal? StaffTuitionWaivers { get; set; }
    }
}
