using System;
using System.Collections.Generic;

namespace Unisol.Web.Entities.Database.UnisolModels
{
    public partial class HrpSalProcessEmployer
    {
        public int Id { get; set; }
        public string EmpNo { get; set; }
        public string Speriod { get; set; }
        public DateTime? Rdate { get; set; }
        public string Personnel { get; set; }
        public string Notes { get; set; }
        public decimal? _005 { get; set; }
        public decimal? _020 { get; set; }
        public decimal? _895 { get; set; }
        public decimal? _595 { get; set; }
        public decimal? _590 { get; set; }
        public decimal? _690 { get; set; }
        public decimal? _015 { get; set; }
        public decimal? _744 { get; set; }
        public decimal? _049 { get; set; }
        public decimal? _745 { get; set; }
        public decimal? _746 { get; set; }
        public decimal? _054 { get; set; }
        public decimal? _767 { get; set; }
        public decimal? _055 { get; set; }
        public decimal? _772 { get; set; }
        public decimal? _056 { get; set; }
        public decimal? _806 { get; set; }
        public decimal? _057 { get; set; }
        public decimal? _896 { get; set; }
        public decimal? _060 { get; set; }
        public decimal? _063 { get; set; }
        public decimal? _776 { get; set; }
        public decimal? _960 { get; set; }
        public decimal? _605 { get; set; }
        public decimal? _102 { get; set; }
        public decimal? _110 { get; set; }
        public decimal? _388 { get; set; }
        public decimal? _905 { get; set; }
        public decimal? _025 { get; set; }
        public decimal? _027 { get; set; }
        public decimal? _036 { get; set; }
        public decimal? _058 { get; set; }
        public decimal? _118 { get; set; }
        public decimal? _311 { get; set; }
        public decimal? _356 { get; set; }
        public decimal? _316 { get; set; }
        public decimal? _586 { get; set; }
        public decimal? _321 { get; set; }
        public decimal? _588 { get; set; }
        public decimal? _610 { get; set; }
        public decimal? _904 { get; set; }
        public decimal? _615 { get; set; }
        public decimal? _622 { get; set; }
        public decimal? _625 { get; set; }
        public decimal? _023 { get; set; }
        public decimal? _632 { get; set; }
        public decimal? _024 { get; set; }
        public decimal? _640 { get; set; }
        public decimal? _641 { get; set; }
        public decimal? _100 { get; set; }
        public decimal? _644 { get; set; }
        public decimal? _647 { get; set; }
        public decimal? _117 { get; set; }
        public decimal? _649 { get; set; }
        public decimal? _652 { get; set; }
        public decimal? _653 { get; set; }
        public decimal? _660 { get; set; }
        public decimal? _694 { get; set; }
        public decimal? _696 { get; set; }
        public decimal? _701 { get; set; }
        public decimal? _703 { get; set; }
        public decimal? _707 { get; set; }
        public decimal? _708 { get; set; }
        public decimal? _710 { get; set; }
        public decimal? _712 { get; set; }
        public decimal? _713 { get; set; }
        public decimal? _718 { get; set; }
        public decimal? _722 { get; set; }
        public decimal? _723 { get; set; }
        public decimal? _725 { get; set; }
        public decimal? _726 { get; set; }
        public decimal? _732 { get; set; }
        public decimal? _733 { get; set; }
        public decimal? _736 { get; set; }
        public decimal? _740 { get; set; }
        public decimal? _742 { get; set; }
        public decimal? _752 { get; set; }
        public decimal? _271 { get; set; }
        public decimal? _345 { get; set; }
        public decimal? _768 { get; set; }
        public decimal? _805 { get; set; }
        public decimal? _822 { get; set; }
        public decimal? _823 { get; set; }
        public decimal? _835 { get; set; }
        public decimal? _836 { get; set; }
        public decimal? _869 { get; set; }
        public decimal? _870 { get; set; }
        public decimal? _013 { get; set; }
        public decimal? _296 { get; set; }
        public decimal? _348 { get; set; }
        public decimal? _702 { get; set; }
        public decimal? _923 { get; set; }
        public decimal? _947 { get; set; }
        public decimal? _949 { get; set; }
        public decimal? _962 { get; set; }
        public decimal? _970 { get; set; }
        public decimal? _328 { get; set; }
        public decimal? _455 { get; set; }
        public decimal? _966 { get; set; }
        public decimal? _968 { get; set; }
        public decimal? _971 { get; set; }
        public decimal? _330 { get; set; }
        public decimal? _384 { get; set; }
        public decimal? _385 { get; set; }
        public decimal? _591 { get; set; }
        public decimal? _592 { get; set; }
        public decimal? _600 { get; set; }
        public decimal? _603 { get; set; }
        public decimal? _607 { get; set; }
        public decimal? _634 { get; set; }
        public decimal? _636 { get; set; }
        public decimal? _637 { get; set; }
        public decimal? _626 { get; set; }
        public decimal? _837 { get; set; }
        public decimal? _415 { get; set; }
        public decimal? Imp { get; set; }
        public decimal? _018 { get; set; }
        public decimal? _065 { get; set; }
        public decimal? _014 { get; set; }
        public decimal? _899 { get; set; }
        public decimal? _0662 { get; set; }
        public decimal? _380 { get; set; }
        public decimal? _335 { get; set; }
        public decimal? _314 { get; set; }
        public decimal? _304 { get; set; }
        public decimal? _259 { get; set; }
        public decimal? _151 { get; set; }
        public decimal? _147 { get; set; }
        public decimal? _898 { get; set; }
        public decimal? _952 { get; set; }
        public decimal? Flu { get; set; }
        public decimal? _617 { get; set; }
        public decimal? _0340 { get; set; }
        public decimal? _889 { get; set; }
        public decimal? _965 { get; set; }
        public decimal? _972 { get; set; }
        public decimal? Bor { get; set; }
        public decimal? _956 { get; set; }
        public decimal? _958 { get; set; }
        public decimal? _144 { get; set; }
        public decimal? _145 { get; set; }
        public decimal? _0890 { get; set; }
        public decimal? _0806 { get; set; }
        public decimal? _140 { get; set; }
        public decimal? Im { get; set; }
        public decimal? Imw { get; set; }
        public decimal? _6411 { get; set; }
        public decimal? _750 { get; set; }
        public decimal? _730 { get; set; }
        public decimal? _731 { get; set; }
        public decimal? Emp { get; set; }
        public decimal? _074 { get; set; }
        public decimal? _111 { get; set; }
        public decimal? _245 { get; set; }
        public decimal? Stl { get; set; }
        public decimal? _0560 { get; set; }
        public decimal? Ukl { get; set; }
        public decimal? Muacd { get; set; }
        public decimal? _006 { get; set; }
        public decimal? Sal { get; set; }
        public decimal? Hlt { get; set; }
        public decimal? Koy { get; set; }
        public decimal? Bam { get; set; }
        public decimal? Sop { get; set; }
        public decimal? Hfck { get; set; }
        public decimal? Arr { get; set; }
        public decimal? Tx { get; set; }
        public decimal? Sum { get; set; }
        public decimal? Op { get; set; }
        public decimal? New { get; set; }
        public decimal? _700 { get; set; }
        public decimal? _788 { get; set; }
        public decimal? _593 { get; set; }
        public decimal? _692 { get; set; }
        public decimal? _691 { get; set; }
        public decimal? _737 { get; set; }
        public decimal? Kei { get; set; }
        public decimal? _053 { get; set; }
        public decimal? _924 { get; set; }
        public decimal? _973 { get; set; }
        public decimal? Un { get; set; }
        public decimal? _921 { get; set; }
        public decimal? _922 { get; set; }
        public decimal? Pres { get; set; }
        public decimal? Co { get; set; }
        public decimal? Court { get; set; }
        public decimal? _0011 { get; set; }
        public decimal? _800 { get; set; }
        public decimal? _801 { get; set; }
        public decimal? _639 { get; set; }
        public decimal? _940 { get; set; }
        public decimal? _115 { get; set; }
        public decimal? Sod { get; set; }
        public decimal? _260 { get; set; }
        public decimal? Bun { get; set; }
        public decimal? Bunl { get; set; }
        public decimal? _789 { get; set; }
        public decimal? _026 { get; set; }
        public decimal? Uap { get; set; }
        public decimal? Mwl { get; set; }
        public decimal? _18inv { get; set; }
        public decimal? Mwss { get; set; }
        public decimal? Mwae { get; set; }
        public decimal? Uoeau { get; set; }
        public decimal? Guss { get; set; }
        public decimal? Gus { get; set; }
        public decimal? Oldmut { get; set; }
        public decimal? Mwd { get; set; }
        public decimal? Ukfosa { get; set; }
        public decimal? Bja { get; set; }
        public decimal? Suma { get; set; }
        public decimal? Lta { get; set; }
        public decimal? Penv { get; set; }
        public decimal? Kcb2 { get; set; }
        public decimal? Cewshg { get; set; }
        public decimal? Cewl { get; set; }
        public decimal? Npa { get; set; }
        public decimal? Npaar { get; set; }
        public decimal? Eca { get; set; }
        public decimal? Ecaar { get; set; }
        public decimal? Hpg { get; set; }
        public decimal? Mvl { get; set; }
        public decimal? Mwsl { get; set; }
        public decimal? Wevc { get; set; }
        public decimal? Wevf { get; set; }
        public decimal? Wevp { get; set; }
        public decimal? Disall { get; set; }
        public decimal? Hall { get; set; }
        public decimal? Wevcfee { get; set; }
        public decimal? Stmsacco { get; set; }
        public decimal? Stimln { get; set; }
        public decimal? Ukreg { get; set; }
        public decimal? Luall { get; set; }
        public decimal? Mmed { get; set; }
        public decimal? Ukl2 { get; set; }
        public decimal? Imp2 { get; set; }
        public decimal? Imp3 { get; set; }
        public decimal? Ptc { get; set; }
        public decimal? Sm { get; set; }
        public decimal? Pssp { get; set; }
        public decimal? Pts { get; set; }
        public decimal? Ptsl { get; set; }
        public decimal? Impref { get; set; }
        public decimal? Plcr { get; set; }
        public decimal? Gra { get; set; }
        public decimal? Lobs { get; set; }
        public decimal? Lobl { get; set; }
    }
}
