using System;
using System.Collections.Generic;

namespace Unisol.Web.Entities.Database.UnisolModels
{
    public partial class ReceiptBook
    {
        public string ReceiptNumber { get; set; }
        public string AdmnNo { get; set; }
        public string CustRef { get; set; }
        public string Names { get; set; }
        public string Account { get; set; }
        public decimal? Amount { get; set; }
        public decimal? Credit { get; set; }
        public string Curr { get; set; }
        public string Ledger { get; set; }
        public string Project { get; set; }
        public string PaymentMode { get; set; }
        public string ModeNumber { get; set; }
        public string Personnel { get; set; }
        public DateTime? Rdate { get; set; }
        public DateTime? Rtime { get; set; }
        public string Notes { get; set; }
        public string Campus { get; set; }
        public string Department { get; set; }
        public DateTime? DocDate { get; set; }
        public decimal? CautionMoney { get; set; }
        public decimal? MiscelaneuosIncome { get; set; }
        public decimal? PrepaidFeesStudents { get; set; }
        public decimal? IgaIncomes { get; set; }
        public decimal? ProvisionForAuditFees { get; set; }
        public decimal? CdfConstituencyDevelopmentFund { get; set; }
        public decimal? BookshopSales { get; set; }
        public decimal? LongTermLiabilities { get; set; }
        public decimal? ApplicationFees { get; set; }
        public decimal? Registration { get; set; }
        public decimal? ActivityFees { get; set; }
        public decimal? StudentMedicalFees { get; set; }
        public decimal? ExaminationsFees { get; set; }
        public decimal? LibraryFees { get; set; }
        public decimal? Supervision { get; set; }
        public decimal? ThesisFees { get; set; }
        public decimal? ComputerFees { get; set; }
        public decimal? TuitionIncome { get; set; }
        public decimal? TeachingPracticeFees { get; set; }
        public decimal? TradeAndOtherPayables { get; set; }
        public decimal? TradeCreditors { get; set; }
        public decimal? ProjectsRetentionMoney { get; set; }
        public decimal? PartTimeLecturers { get; set; }
        public decimal? StaffMedicalClaims { get; set; }
        public decimal? AccruedStatutoryOtherDeductions { get; set; }
        public decimal? OtherLiabilitiesProvisions { get; set; }
        public decimal? Grants { get; set; }
        public decimal? ExchequerGrantsRecurrent { get; set; }
        public decimal? TuitionFees { get; set; }
        public decimal? StudentIdFees { get; set; }
        public decimal? FieldTrips { get; set; }
        public decimal? FieldAttachment { get; set; }
        public decimal? Uoeso { get; set; }
        public decimal? ReferralSupplementary { get; set; }
        public decimal? ReMarkingCharges { get; set; }
        public decimal? OtherStudentRelatedIncome { get; set; }
        public decimal? FarmIncome { get; set; }
        public decimal? CateringIncome { get; set; }
        public decimal? CollaboratingFees { get; set; }
        public decimal? HireOfMotorVehicles { get; set; }
        public decimal? GuestHouse { get; set; }
        public decimal? Fisheries { get; set; }
        public decimal? ConferenceWorkshops { get; set; }
        public decimal? UoesoRent { get; set; }
        public decimal? BridgingFees { get; set; }
        public decimal? VlirCarHire { get; set; }
        public decimal? PhotocopyingBinderyServices { get; set; }
        public decimal? OtherIgaIncome { get; set; }
        public decimal? FinesPenalties { get; set; }
        public decimal? OtherIncomes { get; set; }
        public decimal? AccomodationFees { get; set; }
        public decimal? Amenity { get; set; }
        public decimal? SpecialProject { get; set; }
        public decimal? BankLoans { get; set; }
        public decimal? StaffInsurance { get; set; }
        public decimal? BankTransfers { get; set; }
        public decimal? FieldWorkSupervision { get; set; }
        public decimal? FieldCourse { get; set; }
        public decimal? Eia { get; set; }
        public decimal? StudentsOpeningBalance { get; set; }
        public decimal? LibraryIncome { get; set; }
        public decimal? PayrollRecoveries { get; set; }
        public decimal? Sponsorships { get; set; }
        public decimal? GraduationFees { get; set; }
        public decimal? HelbLoanStudents { get; set; }
        public decimal? HelbBursariesStudents { get; set; }
        public decimal? NetPay { get; set; }
        public decimal? Paye { get; set; }
        public decimal? Nssf { get; set; }
        public decimal? Nhif { get; set; }
        public decimal? HelbLoanRepaymentStaff { get; set; }
        public decimal? Welfares { get; set; }
        public decimal? Pension { get; set; }
        public decimal? UnionDues { get; set; }
        public decimal? SalaryRecovery { get; set; }
        public decimal? CapitalCreditors { get; set; }
        public decimal? WorkshopPractice { get; set; }
        public decimal? CommissionerOfDomesticTaxesWithholdingTax { get; set; }
        public decimal? VatTaxes { get; set; }
        public decimal? RetentionContractor { get; set; }
        public decimal? AgribusinessTradeFair { get; set; }
        public decimal? UnallocatedFee { get; set; }
        public decimal? AccumulatedDepreciationBuilding { get; set; }
        public decimal? AccumulatedDepreciationMotorVehicles { get; set; }
        public decimal? AccumulatedDepreciationFurnitureAndFittings { get; set; }
        public decimal? AccumulatedDepreciationPlantAndEquipment { get; set; }
        public decimal? ProvisionForBadDebts { get; set; }
        public decimal? LegalAttachments { get; set; }
        public decimal? AdministrativeAndRelatedIncomes { get; set; }
        public decimal? GraduationIncome { get; set; }
        public decimal? AccommodationIncome { get; set; }
        public decimal? RentIncome { get; set; }
        public decimal? AccumulatedDepreciationComputersAndAccessories { get; set; }
        public decimal? ResearchFundAccounts { get; set; }
        public decimal? DirectCharges { get; set; }
        public decimal? IncomeTaxPartTimeClaims { get; set; }
        public decimal? WithHoldingVatTaxWhvat { get; set; }
        public decimal? AccumulatedDepreciationLibraryBooks { get; set; }
        public decimal? RentPayable { get; set; }
        public decimal? DonorFundedResearchReceipts { get; set; }
        public decimal? ForestryWoodScience { get; set; }
        public decimal? AccruedExpenses { get; set; }
        public decimal? AccumulatedArmotizationOfLand { get; set; }
        public decimal? AccummulatedArmotizationDepreciation { get; set; }
        public decimal? UoEsoFunds { get; set; }
        public decimal? UoEsoExpenses { get; set; }
        public decimal? Saccos { get; set; }
        public decimal? ResearchAdministrationIncome { get; set; }
        public decimal? ResearchAdministrativeIncome { get; set; }
        public decimal? CustomerPrepayments { get; set; }
        public decimal? UoEsoFundsReceipts { get; set; }
    }
}
