using System;
using System.Collections.Generic;

namespace Unisol.Web.Entities.Database.UnisolModels
{
    public partial class SysSetup
    {
        public string ReceiptNumber { get; set; }
        public string OrgName { get; set; }
        public string SubTitle { get; set; }
        public string Location { get; set; }
        public string Contacts { get; set; }
        public string OrgCurrency { get; set; }
        public string AlbumPath { get; set; }
        public string Smtpserver { get; set; }
        public bool? AllowPrint { get; set; }
        public bool? ThermalPrinter { get; set; }
        public string Thankyou { get; set; }
        public bool? Lock { get; set; }
        public DateTime? LockDate { get; set; }
        public DateTime? StartDate { get; set; }
        public bool? IssueItemBoardOnly { get; set; }
        public bool? AdmitBoardVacOnly { get; set; }
        public bool? AutoInvoiceAtStartup { get; set; }
        public bool? AutoInvoiceOnReg { get; set; }
        public string BoardAcc { get; set; }
        public string FeesStatementMsg { get; set; }
        public string OpeningDate { get; set; }
        public bool? StudentShouldReport { get; set; }
        public bool? AcceptFullFeesOnly { get; set; }
        public bool? RoomFullFeesOnly { get; set; }
        public bool? PrintExamSlip { get; set; }
        public string ExamSlipMsg { get; set; }
        public bool? AutoRoom { get; set; }
        public bool? AutoRoomReport { get; set; }
        public bool? RemRoom { get; set; }
        public bool? IncResRooms { get; set; }
        public string ClassType { get; set; }
        public string ClassStatus { get; set; }
        public string ExcDept { get; set; }
        public decimal? RoomArrears { get; set; }
        public decimal? Tpallowance { get; set; }
        public decimal? OtherTests { get; set; }
        public decimal? Exam { get; set; }
        public int? RoundFinal { get; set; }
        public string ReportMsg { get; set; }
        public string TransMsg { get; set; }
        public string MarkInputDate { get; set; }
        public decimal? Referral { get; set; }
        public string CurVersion { get; set; }
        public string RcreditName { get; set; }
        public string RcreditAcc { get; set; }
        public string Contra { get; set; }
        public string DepreciationAcc { get; set; }
        public string AccumAcc { get; set; }
        public decimal? Tax { get; set; }
        public string MailFrom { get; set; }
        public string CcEmail { get; set; }
        public string Bccemail { get; set; }
        public string EmailMsg { get; set; }
        public string EmailUname { get; set; }
        public string EmailPwd { get; set; }
        public string EmailPort { get; set; }
        public string EmailAuth { get; set; }
        public bool? Ssl { get; set; }
        public bool? AutoPostVch { get; set; }
        public bool? RegUnitOnFullFee { get; set; }
        public bool? MarksInputIsPercent { get; set; }
        public DateTime? UnitRegDeadLine { get; set; }
        public string Obaccount { get; set; }
        public DateTime? NewBankingStartDate { get; set; }
        public string Hbterm { get; set; }
        public string SupSymbol { get; set; }
        public double? SupPercent { get; set; }
        public string RepSymbol { get; set; }
        public double? RepPercent { get; set; }
        public string DisSymbol { get; set; }
        public double? DisPercent { get; set; }
        public string RepeatCaseEvent { get; set; }
        public bool? LastStudNameIsSirname { get; set; }
        public string LibHost { get; set; }
        public string LibUname { get; set; }
        public string LibPwd { get; set; }
        public string LibPort { get; set; }
        public string LibDbname { get; set; }
        public bool? LibConnect { get; set; }
        public string LibBranchCode { get; set; }
        public string LibStudentCat { get; set; }
        public string LibStaffCat { get; set; }
        public bool? Budget { get; set; }
        public string DefaultBudgetDept { get; set; }
        public bool? WageBudgetOnUserDept { get; set; }
        public bool? AutoImprestRecovery { get; set; }
        public int? AutoImpRecGracePeriod { get; set; }
        public int? MaxImprest { get; set; }
        public string Smshost { get; set; }
        public string Smsuname { get; set; }
        public string Smspwd { get; set; }
        public string Smsport { get; set; }
        public string SmsnoFormat { get; set; }
        public string Smsurltemp { get; set; }
        public bool? Smsenabled { get; set; }
        public string LatestVersion { get; set; }
        public bool? BackDatingAllowed { get; set; }
        public DateTime? JeminDate { get; set; }
        public DateTime? CancellationDate { get; set; }
        public string CapitalGrantsAcc { get; set; }
        public bool? SkipFeesBreakDown { get; set; }
        public bool? AppendPayeeOnBt { get; set; }
        public bool? BackLogMarksImp { get; set; }
        public string GradExcStatus { get; set; }
        public bool? GradExcArrears { get; set; }
        public string TheLatestVersion { get; set; }
        public bool? AllowEditOfSupplierInv { get; set; }
        public bool? RoomReserveForOldResidents { get; set; }
        public string Country { get; set; }
        public bool? AutoAdmnNo { get; set; }
        public DateTime ReportingDeadline { get; set; }
        public bool? AutoChequeNo { get; set; }
        public string CustPrepaymentAcc { get; set; }
        public DateTime? LastFeesBalStoredDate { get; set; }
        public int? MinUnitsPerAy { get; set; }
        public int? MaxUnitsPerAy { get; set; }
        public bool? DisplayCtgrades { get; set; }
        public string OtherTestsTreat { get; set; }
        public string GradRoundType { get; set; }
        public string GradRoundTo { get; set; }
        public bool? ComputeIncomeTaxLessFullVat { get; set; }
        public string StudTerminationStatus { get; set; }
        public bool? ComputeBudgetPerPeriod { get; set; }
        public bool? AllowPvedit { get; set; }
        public bool? AllowJvedit { get; set; }
        public string BadDebtAccount { get; set; }
        public bool? NoSkippingOfGradeApprovalLevel { get; set; }
        public string SupType { get; set; }
        public string RepType { get; set; }
        public string DisType { get; set; }
        public bool? ReverseFinalGradeApproval { get; set; }
        public bool? EnablePwdExpiry { get; set; }
        public int? PwdExpiryDays { get; set; }
        public bool? EnforcePwdStrength { get; set; }
		public bool? IsTVET { get; set; }
	}
}
