using System;
using System.Collections.Generic;

namespace Unisol.Web.Entities.Database.UnisolModels
{
    public partial class Users
    {
        public int Id { get; set; }
        public string UserCode { get; set; }
        public string Names { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public DateTime? Edate { get; set; }
        public string Notes { get; set; }
        public byte[] FingerTemplate1 { get; set; }
        public byte[] FingerTemplate2 { get; set; }
        public string Uistyle { get; set; }
        public string Uiskin { get; set; }
        public bool? Closed { get; set; }
        public bool? Administrator { get; set; }
        public bool? Register { get; set; }
        public bool? Applicant { get; set; }
        public bool? Prog { get; set; }
        public bool? Dept { get; set; }
        public bool? Class { get; set; }
        public bool? Board { get; set; }
        public bool? Hostel { get; set; }
        public bool? Items { get; set; }
        public bool? Itemissue { get; set; }
        public bool? Clear { get; set; }
        public bool? Regadmin { get; set; }
        public bool? Arrears { get; set; }
        public bool? FeesState { get; set; }
        public bool? ExamCard { get; set; }
        public bool? StudInv { get; set; }
        public bool? EditStudInv { get; set; }
        public bool? Fees { get; set; }
        public bool? ReceiptBook { get; set; }
        public bool? CustInv { get; set; }
        public bool? EditCustInv { get; set; }
        public bool? Customers { get; set; }
        public bool? Refund { get; set; }
        public bool? Imprest { get; set; }
        public bool? Pcash { get; set; }
        public bool? Payees { get; set; }
        public bool? SupInv { get; set; }
        public bool? Fsuppliers { get; set; }
        public bool? Vpost { get; set; }
        public bool? Banking { get; set; }
        public bool? BankRec { get; set; }
        public bool? Journal { get; set; }
        public bool? FinReports { get; set; }
        public bool? FinState { get; set; }
        public bool? BudSetup { get; set; }
        public bool? BudPeriods { get; set; }
        public bool? BudReport { get; set; }
        public bool? FinAdmin { get; set; }
        public bool? Hod { get; set; }
        public bool? Reporting { get; set; }
        public bool? Performance { get; set; }
        public bool? Marksheet { get; set; }
        public bool? ClassSubject { get; set; }
        public bool? Subjects { get; set; }
        public bool? Tutors { get; set; }
        public bool? AcademicReports { get; set; }
        public bool? Transcripts { get; set; }
        public bool? MarksInput { get; set; }
        public bool? ChangeMarks { get; set; }
        public bool? ExamForms { get; set; }
        public bool? ExamAdmin { get; set; }
        public bool? IssueStock { get; set; }
        public bool? ReceiveStock { get; set; }
        public bool? StockLevels { get; set; }
        public bool? ItemList { get; set; }
        public bool? ItemSet { get; set; }
        public bool? InvReports { get; set; }
        public bool? InvAdmin { get; set; }
        public bool? Bid { get; set; }
        public bool? Awards { get; set; }
        public bool? DeptBudget { get; set; }
        public bool? Orders { get; set; }
        public bool? Req { get; set; }
        public bool? Vouchers { get; set; }
        public bool? ProcReports { get; set; }
        public bool? ProcAdmin { get; set; }
        public bool? ChqPrint { get; set; }
        public bool? ChqReports { get; set; }
        public bool? ReqAlert { get; set; }
        public bool? AssetRegister { get; set; }
        public bool? CheckOut { get; set; }
        public bool? CheckIn { get; set; }
        public bool? CheckOutIn { get; set; }
        public bool? Warranty { get; set; }
        public bool? AssetSearch { get; set; }
        public bool? AssetService { get; set; }
        public bool? AssetReports { get; set; }
        public bool? Assetadmin { get; set; }
        public bool? HrpEmployee { get; set; }
        public bool? HrpEmpCat { get; set; }
        public bool? HrpJobCat { get; set; }
        public bool? HrpDept { get; set; }
        public bool? HrpSection { get; set; }
        public bool? HrpLoc { get; set; }
        public bool? HrpLeave { get; set; }
        public bool? HrpRecruit { get; set; }
        public bool? HrpTimeAtt { get; set; }
        public bool? HrpHire { get; set; }
        public bool? HrpPersReports { get; set; }
        public bool? HrpPersAdmin { get; set; }
        public bool? HrpService { get; set; }
        public bool? HrpSalProcess { get; set; }
        public bool? HrpEarnings { get; set; }
        public bool? HrpDeductions { get; set; }
        public bool? HrpLoan { get; set; }
        public bool? HrpBank { get; set; }
        public bool? HrpFi { get; set; }
        public bool? HrpPayAcc { get; set; }
        public bool? HrpPayGrade { get; set; }
        public bool? HrpSperiod { get; set; }
        public bool? HrpPayReports { get; set; }
        public bool? HrpPayAdmin { get; set; }
        public bool? StudReports { get; set; }
        public bool? ImpAlert { get; set; }
        public bool? StudEnrol { get; set; }
        public bool? HostelBooking { get; set; }
        public bool? BoardAdmin { get; set; }
        public bool? StudentSponsorBd { get; set; }
        public bool? ProvTranscript { get; set; }
        public bool? PayCancel { get; set; }
        public bool? ChqCancel { get; set; }
        public bool? SupPreq { get; set; }
        public bool? Psuppliers { get; set; }
        public bool? Ostatus { get; set; }
        public bool? Rfq { get; set; }
        public string GradeApproval { get; set; }
        public bool? CreditTransfer { get; set; }
        public bool? PayrollComparison { get; set; }
        public DateTime? Rdate { get; set; }
        public string Personnel { get; set; }
        public bool? ReqBudgetCheck { get; set; }
        public bool? SendSms { get; set; }
        public bool? PrintExamCard { get; set; }
        public string EmpNo { get; set; }
        public bool? Hepatient { get; set; }
        public bool? Hevisit { get; set; }
        public bool? Hedrugs { get; set; }
        public bool? Hereports { get; set; }
        public bool? Headmin { get; set; }
        public bool? HeorderTests { get; set; }
        public bool? HetestResults { get; set; }
        public bool? Hediagnosis { get; set; }
        public bool? Heprescription { get; set; }
        public bool? TtstudyProcess { get; set; }
        public bool? TtexamProcess { get; set; }
        public bool? TtstudySchedule { get; set; }
        public bool? TtexamSchedule { get; set; }
        public bool? Ttroom { get; set; }
        public bool? Ttlecturer { get; set; }
        public bool? TtstudyReports { get; set; }
        public bool? TtexamReports { get; set; }
        public bool? Ttadmin { get; set; }
        public bool? ProcPlan { get; set; }
        public bool? ReceiptBookCust { get; set; }
        public bool? ReceiptBookOthers { get; set; }
        public bool? HrpMedicalExp { get; set; }
        public bool? BoardReports { get; set; }
        public DateTime? LastPwdChangeDate { get; set; }
        public bool? ForceChangePwdOnLogin { get; set; }
        public string Campus { get; set; }
        public bool? Gcsmembers { get; set; }
        public bool? Gcsbarcode { get; set; }
        public bool? GcsmemCat { get; set; }
        public bool? Gcsreports { get; set; }
        public bool? GcsentryTrack { get; set; }
        public bool? Gcsadmin { get; set; }
    }
}
